name: capsule_closet_backend
description: "Backend server for Capsule Closet."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  mysql1: ^0.20.0  
  shelf: ^1.4.2 
  shelf_router: ^1.0.0
  mysql_client: ^0.0.27

dev_dependencies:
  lints: ^3.0.0